### ISSUE TITLE
[demo]demo 启动时狂点 menu 键出现 crash(Android 系统5.1.1)

### ISSUE THREAD

**Issue by fuzhengchao** [alibaba/atlas#101]
在 Android 5.1.1系统手机上，demo 启动时狂点 menu 键高频率出现 crash。

`
      java.lang.RuntimeException: Failed to resolve attribute at index 0
          at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:603)
          at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6473)
          at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6642)
          at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:741)
          at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:685)
          at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:62)
          at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
          at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
          at android.support.v7.view.menu.ListMenuPresenter.getMenuView(ListMenuPresenter.java:105)
          at android.support.v7.app.AppCompatDelegateImplV9$PanelFeatureState.getListMenuView(AppCompatDelegateImplV9.java:2030)
          at android.support.v7.app.AppCompatDelegateImplV9.initializePanelContent(AppCompatDelegateImplV9.java:1310)
          at android.support.v7.app.AppCompatDelegateImplV9.openPanel(AppCompatDelegateImplV9.java:1152)
          at android.support.v7.app.AppCompatDelegateImplV9.onKeyUpPanel(AppCompatDelegateImplV9.java:1517)
          at android.support.v7.app.AppCompatDelegateImplV9.onKeyUp(AppCompatDelegateImplV9.java:964)
          at android.support.v7.app.AppCompatDelegateImplV9.dispatchKeyEvent(AppCompatDelegateImplV9.java:958)
          at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:318)
          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2330)
          at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4026)
          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3988)
          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.j`

**Comment by thinkinfish** [comment]
@fuzhengchao 有没有试试手机淘宝正常不

**Comment by fuzhengchao** [comment]
@thinkinfish 手机淘宝是测试了，没有发现这个问题，这个问题貌似和 resource 替换 assetmanager 有关。
