### ISSUE TITLE
[demo]:在小米4s上测试动态部署出现crash

### ISSUE THREAD

**Issue by loveskill** [alibaba/atlas#110]
1、我下载完最新的demo然后进入到demo中的AtlasDemo\app\目录下执行gradle clean assembleDebug publish，将编译出来的app-debug.apk文件拷贝到手机中并安装完成打开。
2、将firstbundle先的strings.xml文件修改成我要的字符串，接着在AtlasDemo\app\目录下执行gradle clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1  然后将build\outputs\tpatch-debug下的patch-1.0.1@1.0.0.tpatch和update.json两个文件拷贝到手机的Android\data\com.taobao.demo\cache目录下，再到软件中去执行动态部署，结果出现如下异常：`dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.taobao.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.demo-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libdalvikpatch.so"
                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.taobao.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.demo-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libdalvikpatch.so"
                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                  at java.lang.System.loadLibrary(System.java:988)
                                                                  at com.uc.browser.aerie.DalvikPatch.patchIfPossible(DalvikPatch.java:12)
                                                                  at android.taobao.atlas.util.DexLoadBooster.init(DexLoadBooster.java:245)
                                                                  at android.taobao.atlas.framework.Atlas.startup(Atlas.java:352)
                                                                  at android.taobao.atlas.bridge.BridgeApplicationDelegate.onCreate(BridgeApplicationDelegate.java:406)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at android.taobao.atlas.startup.AtlasBridgeApplication.onCreate(AtlasBridgeApplication.java:359)
                                                                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                  at android.taobao.atlas.runtime.InstrumentationHook.callApplicationOnCreate(InstrumentationHook.java:1048)
                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
                                                                  at android.app.ActivityThread.access$1500(ActivityThread.java:154)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)`

**Comment by hwjump** [comment]
请参考 #60    这里不是crash的地方。这里是warning。请再看一下具体的crash

**Comment by loveskill** [comment]
这个问题是我误报，不好意思。我具体看了，报给我的是找不到/storage/sdcard1/Android/data/com.taobao.demo/cache/底下的文件，我重启我的手机之后就可以动态部署成功了，是文件同步问题。

**Comment by lixi0912** [comment]
arm64 下找不到 libdalvikpatch.so

ndk{
            abiFilters "armeabi-v7a"
}

**Comment by hwjump** [comment]
arm64  不需要用到libdalvikpatch.so     缺少它 只会打个异常log，不会crash。
