### ISSUE TITLE
DataBinding 不支持扩展Component

### ISSUE THREAD

**Issue by mockji** [alibaba/atlas#204]
自定义BinderApdapter，以及不同的Component，在不同的Component中返回不同的BinderAdapter
这种情况会导致闪退

原因是生成的Component类被直接去掉了，而宿主工程的Component类又不包含对应的方法

日志如下：

 java.lang.NoSuchMethodError: No interface method getMyBindingAdapter()Lcom/taobao/databindbundle/databind/MyBindingAdapter; in class Landroid/databinding/DataBindingComponent; or its super classes (declaration of 'android.databinding.DataBindingComponent' appears in /data/app/com.taobao.demo-1/base.apk)
                                                                     at com.taobao.databindbundle.databinding.BundleDatabindMainBinding.executeBindings(BundleDatabindMainBinding.java:186)
                                                                     at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:379)
                                                                     at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:351)
                                                                     at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:178)
                                                                     at android.databinding.ViewDataBinding$5.onViewAttachedToWindow(ViewDataBinding.java:146)
                                                                     at android.view.View.dispatchAttachedToWindow(View.java:15560)
                                                                     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2955)
                                                                     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
                                                                     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
                                                                     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1650)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1366)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6768)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
                                                                     at android.os.Handler.handleCallback(Handler.java:761)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                     at android.os.Looper.loop(Looper.java:156)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6577)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by lilongAAAA** [comment]
多些反馈，has fixed in gradle_4.0.1 branch
