### ISSUE TITLE
某些机型，dialog.show时，报资源找不到，Resource ID #0x0

### ISSUE THREAD

**Issue by leidroid** [alibaba/atlas#206]
错误大致日志如下：
android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:255)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2187)
	at android.content.res.Resources.getLayout(Resources.java:1178)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at android.support.v7.app.AppCompatDelegateImplV9.b(SourceFile:292)
	at android.support.v7.app.AppCompatDialog.setContentView(SourceFile:83)
	at android.support.v7.app.AlertDialog.onCreate(SourceFile:1225)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:514)
	at android.app.Dialog.show(Dialog.java:380)
请问什么原因引起的

**Comment by lilongAAAA** [comment]
创建alertdialog请设置theme进去
