### ISSUE TITLE
Android 4.4.4及以下系统, 同一个 Bundle 中的两个 Activity 之间跳转用 Intent 传递自定义类会 crash

### ISSUE THREAD

**Issue by huaf22** [alibaba/atlas#211]
`
Caused by: java.lang.RuntimeException: Parcelable encounteredClassNotFoundException reading a Serializable object (name = com.demo.shopping.model.a)
at android.os.Parcel.readSerializable(Parcel.java:2226)
at android.os.Parcel.readValue(Parcel.java:2071)
at android.os.Parcel.readListInternal(Parcel.java:2362)
at android.os.Parcel.readArrayList(Parcel.java:1710)
at android.os.Parcel.readValue(Parcel.java:2041)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
at android.os.Bundle.unparcel(Bundle.java:249)
at android.os.Bundle.containsKey(Bundle.java:299)
at com.demo.anp.a(SourceFile:43)
at com.demo.anp.a(SourceFile:21)
at com.demo.anp.a(SourceFile:57)   					
at com.demo.shopping.ui.shop.ai$4.a(SourceFile:70)  
at com.demo.shopping.ui.shop.ai$4.get(SourceFile:67)
at com.demo.and.a(SourceFile:163)                      
at com.demo.shopping.ui.shop.ai.d(SourceFile:67)
at com.demo.shopping.ui.shop.ao.a(SourceFile:24)
at com.demo.shopping.ui.shop.ao.get(SourceFile:10)  
at com.demo.shopping.ui.shop.ap.a(SourceFile:40)
at com.demo.shopping.ui.shop.ap.injectMembers(SourceFile:10)    
at com.demo.shopping.ui.shop.d.a(SourceFile:42)               
... 24 more
Caused by: java.lang.ClassNotFoundException: com.demo.shopping.biz.model.a     
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:2263)
at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1641)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782)
at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
at android.os.Parcel.readSerializable(Parcel.java:2220)
... 43 more
Caused by: java.lang.NoClassDefFoundError: com/demo/shopping/biz/model/a
... 53 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.demo.shopping.biz.model.a" on path: DexPathList[[zip file "/data/app/com.demo-1.apk", zip file "/data/data/com.demo/code_cache/secondary-dexes/com.demo-1.apk.classes2.zip", zip file "/data/data/com.demo/code_cache/secondary-dexes/com.demo-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/com.demo-1, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
... 53 more
`

**Comment by huaf22** [comment]
补充： 这个自定义类也是定义在同一个 Bundle 中的

**Comment by hwjump** [comment]
见  https://github.com/alibaba/atlas/issues/167  这个issue
