### ISSUE TITLE
接入atlas后，app中的微信分享不能使用，有遇到该问题的没有？

### ISSUE THREAD

**Issue by oneapp1e** [alibaba/atlas#216]
12-21 10:33:15.104 1828-1828/com.v.zy W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err: java.lang.Throwable: {"transaction":"webpage1513823594822","req":"e","errCode":-6}
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at cn.sharesdk.wechat.utils.i.a(WechatHandler.java:119)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at cn.sharesdk.wechat.utils.h.a(WechatCore.java:290)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at cn.sharesdk.wechat.utils.j.a(WechatHelper.java:701)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at cn.sharesdk.wechat.utils.WechatHandlerActivity.onCreate(WechatHandlerActivity.java:33)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.app.Activity.performCreate(Activity.java:6351)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:666)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.app.ActivityThread.access$1000(ActivityThread.java:166)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:269)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.os.Looper.loop(Looper.java:148)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5628)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
12-21 10:33:15.124 1828-1828/com.v.zy W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
12-21 10:33:15.144 1828-1828/com.v.zy W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection

**Comment by oneapp1e** [comment]
配置有问题，没有打正确签名包
