### ISSUE TITLE
[use]: 跨bundle使用Fragment 失败

### ISSUE THREAD

**Issue by candledragle** [alibaba/atlas#233]
配置过程：
参考官方[跨bundle代码复用和通信](https://alibaba.github.io/atlas/guide-for-use/bundleCommunicate.html)配置如下

firstbundle 下UseremoteActivity 代码如下

```
   
public class UseremoteActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_useremote);

        RemoteFactory.requestRemote(RemoteFragment.class, this, new Intent("atlas.fragment.intent.action.SECOND_RICH"),
                new RemoteFactory.OnRemoteStateListener<RemoteFragment>() {
            @Override
            public void onRemotePrepared(RemoteFragment iRemoteContext) {
                /*FrameLayout layout = (FrameLayout) findViewById(R.id.fl_content);
                FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
                layout.addView(iRemoteContext,params);*/
                getSupportFragmentManager().beginTransaction().add(R.id.fl_content,iRemoteContext).commit();

            }

            @Override
            public void onFailed(String s) {
                Log.e("UserRemoteActivity",s);
            }
        });

    }
}
```
secondbundle 下的TestFragment 代码如下

```
public class TestFragment extends Fragment implements IRemote {
    @Override
    public Bundle call(String commandName, Bundle args, IResponse callback) {
        return null;
    }

    @Override
    public <T> T getRemoteInterface(Class<T> interfaceClass, Bundle args) {
        return null;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.fragment_plus_one, container, false);
        return view;
    }
}
```
secondbundle 的清单文件

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.taobao.secondbundle">

    
    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:allowBackup="true"
        android:supportsRtl="true">
        <activity
            android:theme="@style/AppTheme.NoActionBar"
            android:name="com.taobao.secondbundle.SecondBundleActivity"></activity>
        
        <meta-data android:name="atlas.fragment.intent.action.SECOND_RICH" android:value="com.taobao.secondbundle.TestFragment"/>
    </application>

</manifest>
错误日志：

```
01-20 13:41:54.708 32446-32446/com.taobao.demo I/Timeline: Timeline: Activity_launch_request time:63954371
01-20 13:41:54.818 32446-32446/com.taobao.demo E/UserRemoteActivity: no match remote-item with intent : Intent { act=atlas.fragment.intent.action.SECOND_RICH }
01-20 13:41:54.818 32446-32511/com.taobao.demo W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.taobao.atlas.bundleInfo.BundleListing$BundleInfo.getTotalDependency()' on a null object reference
01-20 13:41:54.818 32446-32511/com.taobao.demo W/System.err:     at android.taobao.atlas.framework.BundleInstaller.call(BundleInstaller.java:604)
01-20 13:41:54.818 32446-32511/com.taobao.demo W/System.err:     at android.taobao.atlas.framework.BundleInstaller$2.run(BundleInstaller.java:521)
01-20 13:41:54.818 32446-32511/com.taobao.demo W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
01-20 13:41:54.818 32446-32511/com.taobao.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-20 13:41:54.818 32446-32511/com.taobao.demo W/System.err:     at android.os.Looper.loop(Looper.java:135)
01-20 13:41:54.818 32446-32511/com.taobao.demo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
01-20 13:41:54.818 32446-32446/com.taobao.demo D/ActivityThreadInjector: clearCachedDrawables.
01-20 13:41:54.868 32446-32446/com.taobao.demo E/BundleInstaller: notify finish [null]
01-20 13:41:54.868 32446-32446/com.taobao.demo E/UserRemoteActivity: install bundle failed: null

```

**Comment by candledragle** [comment]
```

{
	"bundleInfo":[
		{
			"isInternal":true,
			"contentProviders":[],
			"remoteFragments":{},
			"dependency":[
				"com.taobao.publicBundle"
			],
			"receivers":[],
			"activities":[
				"com.taobao.firstbundle.FirstBundleActivity",
				"com.taobao.firstbundle.UseremoteActivity",
				"com.taobao.firstbundle.WebViewDemoActivity"
			],
			"pkgName":"com.taobao.firstbundle",
			"remoteTransactors":{},
			"remoteViews":{},
			"services":[
				"com.taobao.firstbundle.FirstBundleService"
			],
			"unique_tag":"2afeqp24xk3fo",
			"version":"1.0.0@1.0.1"
		},
		{
			"isInternal":true,
			"contentProviders":[],
			"remoteFragments":{
				"atlas.fragment.intent.action.SECOND_RICH":"com.taobao.secondbundle.TestFragment"
			},
			"dependency":[],
			"receivers":[],
			"activities":[
				"com.taobao.secondbundle.SecondBundleActivity",
				"com.taobao.secondbundlelibrary.SecondbundleShareActivity"
			],
			"pkgName":"com.taobao.secondbundle",
			"remoteTransactors":{},
			"remoteViews":{},
			"services":[],
			"unique_tag":"njvbctcqm212",
			"version":"1.0.0@1.0.0"
		},
		{
			"isInternal":true,
			"contentProviders":[],
			"remoteFragments":{},
			"dependency":[],
			"receivers":[],
			"activities":[],
			"pkgName":"com.taobao.publicBundle",
			"remoteTransactors":{},
			"remoteViews":{},
			"services":[],
			"unique_tag":"20scnecn99mhy",
			"version":"1.0.0@1.0.0"
		}
	],
	"outApp":false,
	"autoStartBundles":"firstbundle",
	"unit_tag":"hkb4hs9t861z",
	"preLaunch":""
}


```

**Comment by hwjump** [comment]
atlas_core : 5.0.7.55
atlasplugin: 2.3.3.rc41     remoteview是需要atlas_core和atlasplugin配合的。    请确认是用的版本是release以上的版本。

具体请参考 https://alibaba.github.io/atlas/guide-for-use/bundleCommunicate.html

**Comment by 18311023368** [comment]
同问

**Comment by 18311023368** [comment]
com.taobao.android:atlas_core:5.0.8.0-rc46@aar    版本号改一下就行了
