### ISSUE TITLE
执行命令： gradlew clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1总是失败

### ISSUE THREAD

**Issue by Tanglonglong** [alibaba/atlas#256]
1. AtlasDemo ：执行命令： gradlew clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1总是失败

 异常日志如下：
do patch:E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\unzip\new.apk\lib\x86\libdexinterpret.so
[BundleDiffType]libcom_taobao_databindbundle.so:NONE
>>> start to process bundle for patch libcom_taobao_databindbundle >> difftype NONE createALl:true
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:480)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$4.call(TPatchTool.java:1046)
        at com.taobao.android.tools.TPatchTool$4.call(TPatchTool.java:1043)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:480)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1093)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1085)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:482)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$4.call(TPatchTool.java:1046)
        at com.taobao.android.tools.TPatchTool$4.call(TPatchTool.java:1043)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:482)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1093)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1085)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
>>> fininsh to process bundle for patch libcom_taobao_databindbundle >> difftype NONE consume:5339
[BundleDiffType]libcom_taobao_firstbundle.so:NONE
>>> start to process bundle for patch libcom_taobao_firstbundle >> difftype NONE createALl:true
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:480)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1093)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1085)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:482)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1093)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1085)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
>>> fininsh to process bundle for patch libcom_taobao_remotebunle >> difftype NONE consume:5369
[BundleDiffType]libcom_taobao_publicBundle.so:NONE
>>> start to process bundle for patch libcom_taobao_publicBundle >> difftype NONE createALl:true
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:480)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1093)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1085)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:482)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1093)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1085)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
>>> fininsh to process bundle for patch libcom_taobao_publicBundle >> difftype NONE consume:989
[BundleDiffType]libcom_taobao_secondbundle.so:NONE
>>> start to process bundle for patch libcom_taobao_secondbundle >> difftype NONE createALl:true
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:480)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1093)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1085)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
java.io.IOException: Cannot run program "unzip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.doBundleDexPatch(TPatchTool.java:482)
        at com.taobao.android.tools.TPatchTool.doBundlePatch(TPatchTool.java:414)
        at com.taobao.android.tools.TPatchTool.processBundleFiles(TPatchTool.java:400)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1093)
        at com.taobao.android.tools.TPatchTool$6.call(TPatchTool.java:1085)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
>>> fininsh to process bundle for patch libcom_taobao_firstbundle >> difftype NONE consume:1033
>>> fininsh to process bundle for patch libcom_taobao_secondbundle >> difftype NONE consume:740
Expiring Daemon because JVM Tenured space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
Expiring Daemon because JVM Tenured space is exhausted
java.io.IOException: Cannot run program "zip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp\libcom_taobao_maindex"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.createTPatchFile(TPatchTool.java:344)
        at com.taobao.android.tools.TPatchTool.doPatch(TPatchTool.java:1108)
        at com.taobao.android.PatchManager.doPatch(PatchManager.java:39)
        at com.taobao.android.builder.tasks.tpatch.TPatchTask.doTPatch(TPatchTask.java:314)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 40 more
java.io.IOException: Cannot run program "zip" (in directory "E:\StudyTwo\atlas-master\atlas-demo\AtlasDemo\app\build\outputs\tpatch-debug\tpatch-tmp"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.taobao.android.utils.CommandUtils.exec(CommandUtils.java:19)
        at com.taobao.android.tools.TPatchTool.createTPatchFile(TPatchTool.java:357)
        at com.taobao.android.tools.TPatchTool.doPatch(TPatchTool.java:1108)
        at com.taobao.android.PatchManager.doPatch(PatchManager.java:39)
        at com.taobao.android.builder.tasks.tpatch.TPatchTask.doTPatch(TPatchTask.java:314)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 40 more
:app:createTPatchDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createTPatchDebug'.
> com.taobao.firstbundle内容发生了变化,但是unitTag一致2afeqp24xk3fo,请修改版本做集成

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by Ellio007** [comment]
老哥，你是不是没修改firstbundle里的build.gradle文件的版本号？

**Comment by Tanglonglong** [comment]
我 试试

**Comment by hwjump** [comment]
还有问题么，最好参照demo目录下的那个txt文件，操作哈
