### ISSUE TITLE
windows编译通过,运行报错: ClassNotFoundException BaselineInfoManager

### ISSUE THREAD

**Issue by wwd0** [alibaba/atlas#264]
我使用如下配置 : com.taobao.android:atlasplugin:3.0.1-rc43,
com.taobao.android:atlas_core:5.0.8.1-rc1@aar
我参考AtlasDemo配置的本公司app编译通过，但是一运行报错，错误详细信息如下：
Unable to instantiate application android.taobao.atlas.startup.AtlasBridgeApplication: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.versionInfo.BaselineInfoManager" on path: DexPathList[[zip file "/data/app/com.gvn.mbl.android.wc.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.gvn.mbl.android.wc.app-1, /vendor/lib, /system/lib]]
			   at android.app.LoadedApk.makeApplication(LoadedApk.java:509)
			   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4314)
			   at android.app.ActivityThread.access$1500(ActivityThread.java:138)
			   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
			   at android.os.Handler.dispatchMessage(Handler.java:102)
			   at android.os.Looper.loop(Looper.java:136)
			   at android.app.ActivityThread.main(ActivityThread.java:5016)
			   at java.lang.reflect.Method.invokeNative(Native Method)
			   at java.lang.reflect.Method.invoke(Method.java:515)
			   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
			   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
			   at dalvik.system.NativeStart.main(Native Method)
			Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.versionInfo.BaselineInfoManager" on path: DexPathList[[zip file "/data/app/com.gvn.mbl.android.wc.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.gvn.mbl.android.wc.app-1, /vendor/lib, /system/lib]]
			   at android.taobao.atlas.startup.AtlasBridgeApplication.attachBaseContext(AtlasBridgeApplication.java:337)
			   at android.app.Application.attach(Application.java:185)
			   at android.app.Instrumentation.newApplication(Instrumentation.java:991)
			   at android.app.Instrumentation.newApplication(Instrumentation.java:975)
			   at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
			   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4314) 
			   at android.app.ActivityThread.access$1500(ActivityThread.java:138) 
			   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261) 
			   at android.os.Handler.dispatchMessage(Handler.java:102) 
			   at android.os.Looper.loop(Looper.java:136) 
			   at android.app.ActivityThread.main(ActivityThread.java:5016) 
			   at java.lang.reflect.Method.invokeNative(Native Method) 
			   at java.lang.reflect.Method.invoke(Method.java:515) 
			   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
			   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
			   at dalvik.system.NativeStart.main(Native Method) 
			Caused by: java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.versionInfo.BaselineInfoManager" on path: DexPathList[[zip file "/data/app/com.gvn.mbl.android.wc.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.gvn.mbl.android.wc.app-1, /vendor/lib, /system/lib]]
			   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
			   at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
			   at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
			   at android.taobao.atlas.startup.AtlasBridgeApplication.attachBaseContext(AtlasBridgeApplication.java:314)
			   at android.app.Application.attach(Application.java:185) 
			   at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
			   at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
			   at android.app.LoadedApk.makeApplication(LoadedApk.java:504) 
			   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4314) 
			   at android.app.ActivityThread.access$1500(ActivityThread.java:138) 
			   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261) 
			   at android.os.Handler.dispatchMessage(Handler.java:102) 
			   at android.os.Looper.loop(Looper.java:136) 
			   at android.app.ActivityThread.main(ActivityThread.java:5016) 
			   at java.lang.reflect.Method.invokeNative(Native Method) 
			   at java.lang.reflect.Method.invoke(Method.java:515) 
			   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
			   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
			   at dalvik.system.NativeStart.main(Native Method)

**Comment by wwd0** [comment]
我反编译了apk, 是有这个类文件的： android.content.pm.PackageInfo.BaselineInfoManager
AtlasDemo中 multiDexEnabled = false， 但我公司app里得要设为true, 不然编不过。方法数超过65535
