### ISSUE TITLE
windows下AtlasDemo将multiDexEnabled=true运行崩溃

### ISSUE THREAD

**Issue by wwd0** [alibaba/atlas#265]
我使用的是 gradle_4.0.1 分支的 AtlasDemo, 
在app目录下的build.gradle文件中将 multiDexEnabled=false 改为true
编译通过，但一运行app就会崩溃。报如下错误：
Unable to instantiate application android.taobao.atlas.startup.AtlasBridgeApplication: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.versionInfo.BaselineInfoManager"

**Comment by lilongAAAA** [comment]
能否apk attch上来

**Comment by perhapsatron** [comment]
我这里碰到类似的问题，是没有将这个类打到主dex中，keep文件里加了一些启动必须的类之后就好了。希望新版本的插件能让人省掉这步操作

**Comment by zhoujunyou** [comment]
出现了同样的问题
08-16 23:37:51.587 22481-22481/? D/dalvikvm: Late-enabling CheckJNI
08-16 23:37:51.587 22481-22481/? I/Zygote: fake Product info cn.mwee.android.atlasapp not matched any pattern
08-16 23:37:51.639 22481-22481/cn.mwee.android.atlasapp E/RuntimeUtils: - RuntimeUtils init: mEnabled=true
08-16 23:37:51.639 22481-22481/cn.mwee.android.atlasapp I/VMUtil: VM with version 1.6.0 does not have ART support
08-16 23:37:51.639 22481-22481/cn.mwee.android.atlasapp D/dalvikvm: Trying to load lib /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikhack.so 0x42e1cf98
08-16 23:37:51.671 22481-22481/cn.mwee.android.atlasapp D/houdini: [22481] Loading library(version: 4.0.8.45720 RELEASE)... successfully.
08-16 23:37:51.675 22481-22481/cn.mwee.android.atlasapp D/dalvikvm: Added shared lib /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikhack.so 0x42e1cf98
08-16 23:37:51.687 22481-22481/cn.mwee.android.atlasapp E/RuntimeUtils: - RuntimeUtils init: success=true
08-16 23:37:51.687 22481-22481/cn.mwee.android.atlasapp E/AndroidRuntime: class com.taobao.android.runtime.Dex2OatService
08-16 23:37:51.687 22481-22481/cn.mwee.android.atlasapp D/dalvikvm: Trying to load lib /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikpatch.so 0x42e1cf98
    Added shared lib /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikpatch.so 0x42e1cf98
    No JNI_OnLoad found in /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikpatch.so 0x42e1cf98, skipping init
08-16 23:37:51.711 22481-22481/cn.mwee.android.atlasapp E/DALVIK_PATCH: vm:dalvik
    Find dvmGlobalsPtr successed!
08-16 23:37:51.715 22481-22481/cn.mwee.android.atlasapp D/DALVIK_PATCH: [4][0x8]Not readable! b
    [6][0x8]Not readable! b
    [10][0x18]Not readable! b
    [11][0x10]Not readable! b
08-16 23:37:51.719 22481-22481/cn.mwee.android.atlasapp D/DALVIK_PATCH: [14][0x14]Not readable! b
    [15][0x8]Not readable! b
    [16][0x10]Not readable! b
    [17][0xc]Not readable! b
    [19][0x0]Not readable! b
    [20][0xfffd8426]Not readable! b
    [21][0x0]Not readable! b
    [22][0x0]Not readable! b
    [23][0xffffc48e]Not readable! b
    [24][0x0]Not readable! b
    [26][0x3]Not readable! b
    [27][0x0]Not readable! b
    [29][0xfc]Not readable! b
    [31][0x2]Not readable! b
08-16 23:37:51.723 22481-22481/cn.mwee.android.atlasapp D/DALVIK_PATCH: [32][0x200]Not readable! b
    [33][0xc800]Not readable! b
    [34][0x0]Not readable! b
    [36][0x3]Not readable! b
    [37][0x10]Not readable! b
    [38][0xc800]Not readable! b
    [39][0x0]Not readable! b
    [40][0x0]Not readable! b
    [43][0x10]Not readable! b
    [44][0x400]Not readable! b
    [45][0x0]Not readable! b
08-16 23:37:51.727 22481-22481/cn.mwee.android.atlasapp D/DALVIK_PATCH: [47][0x0]Not readable! b
    [48][0xffffe24a]Not readable! b
    [56][0x1]Not readable! b
    [57][0xf]Not readable! b
08-16 23:37:51.727 22481-22481/cn.mwee.android.atlasapp E/DALVIK_PATCH: ***********************************************
    => LinearAllocHdr:[0x81489520]
    => curOffset[3477172]
    => mapAddr[0x6e9f6000]
    => mapLength[16777216]
    => firstOffset[4100]
    => mapAddr: [0x6e9f6000]
08-16 23:37:51.731 22481-22481/cn.mwee.android.atlasapp E/DALVIK_PATCH: ***********************************************
    Search LinearAllocHdr cost: 16 ms!
    LinearAllocHdr.mapLength >= 16777216, don't patch dalvik!
08-16 23:37:51.731 22481-22481/cn.mwee.android.atlasapp D/DalvikPatch: - patchIfPossible: adjustLinearAlloc=-303
08-16 23:37:51.735 22481-22481/cn.mwee.android.atlasapp D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-16 23:37:51.735 22481-22481/cn.mwee.android.atlasapp W/dalvikvm: VFY: unable to resolve static field 76 (PREVIEW_SDK_INT) in Landroid/os/Build$VERSION;
08-16 23:37:51.735 22481-22481/cn.mwee.android.atlasapp D/dalvikvm: VFY: replacing opcode 0x60 at 0x0018
    DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-16 23:37:51.735 22481-22481/cn.mwee.android.atlasapp W/dalvikvm: VFY: unable to resolve static field 76 (PREVIEW_SDK_INT) in Landroid/os/Build$VERSION;
08-16 23:37:51.735 22481-22481/cn.mwee.android.atlasapp D/dalvikvm: VFY: replacing opcode 0x60 at 0x000a
08-16 23:37:51.735 22481-22481/cn.mwee.android.atlasapp D/AndroidRuntime: Shutting down VM
08-16 23:37:51.739 22481-22481/cn.mwee.android.atlasapp W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x42b53b20)
08-16 23:37:51.739 22481-22481/cn.mwee.android.atlasapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.mwee.android.atlasapp, PID: 22481
    java.lang.RuntimeException: Unable to instantiate application android.taobao.atlas.startup.AtlasBridgeApplication: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.versionInfo.BaselineInfoManager" on path: DexPathList[[zip file "/data/app/cn.mwee.android.atlasapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/cn.mwee.android.atlasapp-1, /system/lib, /system/lib/arm]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4351)
        at android.app.ActivityThread.access$1600(ActivityThread.java:137)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5089)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.versionInfo.BaselineInfoManager" on path: DexPathList[[zip file "/data/app/cn.mwee.android.atlasapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/cn.mwee.android.atlasapp-1, /system/lib, /system/lib/arm]]
        at android.taobao.atlas.startup.AtlasBridgeApplication.attachBaseContext(AtlasBridgeApplication.java:337)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4351) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:137) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.versionInfo.BaselineInfoManager" on path: DexPathList[[zip file "/data/app/cn.mwee.android.atlasapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/cn.mwee.android.atlasapp-1, /system/lib, /system/lib/arm]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at android.app.CloneClassLoader.findClass(CloneClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.taobao.atlas.startup.AtlasBridgeApplication.attachBaseContext(AtlasBridgeApplication.java:314)
        at android.app.Application.attach(Application.java:181) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4351) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:137) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
        at dalvik.system.NativeStart.main(Native Method) 
08-16 23:37:52.051 22481-22481/cn.mwee.android.atlasapp I/Process: Sending signal. PID: 22481 SIG: 9

**Comment by zhoujunyou** [comment]
[atlasapp-debug.zip](https://github.com/alibaba/atlas/files/2295633/atlasapp-debug.zip)
这是apk
