### ISSUE TITLE
混淆打包失败

### ISSUE THREAD

**Issue by zhangfeifeilz** [alibaba/atlas#278]
Caused by: java.io.IOException: proguard.ParseException: Expecting class path separator ':' before '/workspace/app/build/intermediates/awb-classes/release/workspace-advertbundle' in line 1 of file '/Users/jingyao/.jenkins/jobs/用户端(新)/workspace/app/build/outputs/mapping/release/awb_inout_config.cfg'
18:01:57.110 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:283)
18:01:57.110 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:63)
18:01:57.110 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:173)
18:01:57.110 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.builder.tasks.Job.runTask(Job.java:48)
18:01:57.110 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
18:01:57.110 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:225)
18:01:57.110 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: proguard.ParseException: Expecting class path separator ':' before '/workspace/app/build/intermediates/awb-classes/release/workspace-advertbundle' in line 1 of file '/Users/jingyao/.jenkins/jobs/H用户端(新)/workspace/app/build/outputs/mapping/release/awb_inout_config.cfg'
18:01:57.111 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.taobao.android.builder.tools.proguard.KeepOnlyConfigurationParser.parseClassPathArgument(KeepOnlyConfigurationParser.java:616)
18:01:57.111 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.taobao.android.builder.tools.proguard.KeepOnlyConfigurationParser.parse(KeepOnlyConfigurationParser.java:355)
18:01:57.111 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.taobao.android.builder.tasks.transform.AtlasProguardTransform.applyLibConfigurationFile(AtlasProguardTransform.java:511)
18:01:57.111 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.taobao.android.builder.tasks.transform.AtlasProguardTransform.applyConfigurationFile(AtlasProguardTransform.java:476)
18:01:57.111 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:245)
18:01:57.111 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 5 more
18:01:57.111 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
18:01:57.111 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
18:01:57.111 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
18:01:57.112 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
18:01:57.112 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 2 mins 25.577 secs

**Comment by hwjump** [comment]
检查下自己的混淆配置文件格式。
