### ISSUE TITLE
[use]:动态部署更新时，抛出异常，请问是什么原因？

### ISSUE THREAD

**Issue by yunsimon** [alibaba/atlas#279]
插件使用：atlas_core:5.1.0.0  atlasupdate:1.1.4.21
抛出异常如下：
java.lang.NullPointerException: Attempt to get length of null array
	at android.taobao.atlas.startup.patch.releaser.BundleReleaser.dexOptimization(BundleReleaser.java:431)
	at android.taobao.atlas.startup.patch.releaser.BundleReleaser.handleMsg(BundleReleaser.java:310)
	at android.taobao.atlas.startup.patch.releaser.BundleReleaser.access$000(BundleReleaser.java:235)
	at android.taobao.atlas.startup.patch.releaser.BundleReleaser$1.handleMessage(BundleReleaser.java:277)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by yunsimon** [comment]
找到原因了，是更新被放到主线程执行了
