### ISSUE TITLE
[use]:生成动态部署包时，产生异常

### ISSUE THREAD

**Issue by yunsimon** [alibaba/atlas#281]
插件使用：atlas_core:5.1.0.0  atlasupdate:1.1.4.21
运行“gradlew clean assembleDebug -DapVersion= -DversionName=“生成动态部署包时，产生异常下列异常，请问是什么原因？

Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing process C:\Users\gjy\.gradle\caches\modules-2\files-2
.1\com.taobao.android\aapt\2.3.1.rc4\593df1ae86cbee190c8fbd096adfb1b56f76d41d\aapt-2.3.1.rc4\aapt.exe with arguments {package -f --no-crunch -I C:\Users\guojianyun\AppDat
a\Local\Android\Sdk\platforms\android-26\android.jar -M C:\work\VideoWallpaper_Atlas\app\build\intermediates\res\AndroidManifest.xml -S C:\work\VideoWallpaper_Atlas\app\b
uild\intermediates\tpatch\release\diff-res\res -A C:\work\VideoWallpaper_Atlas\app\build\intermediates\tpatch\release\diff-res\assets -F C:\work\VideoWallpaper_Atlas\app\
build\intermediates\res\resources-release-diff.ap_ -0 apk -B C:\work\VideoWallpaper_Atlas\app\build\intermediates\exploded-ap\android.apk --no-version-vectors}
        at com.taobao.android.builder.tasks.tpatch.TPatchDiffResAPBuildTask.doAction(TPatchDiffResAPBuildTask.java:369)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
Caused by: com.android.ide.common.process.ProcessException: Error while executing process C:\Users\guojianyun\.gradle\caches\modules-2\files-2.1\com.taobao.android\aapt\2
.3.1.rc4\593df1ae86cbee190c8fbd096adfb1b56f76d41d\aapt-2.3.1.rc4\aapt.exe with arguments {package -f --no-crunch -I C:\Users\guojianyun\AppData\Local\Android\Sdk\platform
s\android-26\android.jar -M C:\work\VideoWallpaper_Atlas\app\build\intermediates\res\AndroidManifest.xml -S C:\work\VideoWallpaper_Atlas\app\build\intermediates\tpatch\re
lease\diff-res\res -A C:\work\VideoWallpaper_Atlas\app\build\intermediates\tpatch\release\diff-res\assets -F C:\work\VideoWallpaper_Atlas\app\build\intermediates\res\reso
urces-release-diff.ap_ -0 apk -B C:\work\VideoWallpaper_Atlas\app\build\intermediates\exploded-ap\android.apk --no-version-vectors}
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:74)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:49)
        at com.android.builder.core.AtlasBuilder.processResources(AtlasBuilder.java:561)
        at com.taobao.android.builder.tasks.tpatch.TPatchDiffResAPBuildTask.doAction(TPatchDiffResAPBuildTask.java:360)
        ... 78 more
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\guojianyun\.gradle\caches\modules-2\files-2.1\com.taobao.android\aapt\2.3.1.rc4\593df1ae8
6cbee190c8fbd096adfb1b56f76d41d\aapt-2.3.1.rc4\aapt.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:369)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:47)
        ... 80 more

**Comment by hwjump** [comment]
命令行增加 --info --debug --stacktrace 看具体是哪个资源处理失败了。

**Comment by yunsimon** [comment]
带上这些参数，也是没提示哪个资源处理失败

**Comment by yunsimon** [comment]
后续没发现这个问题，先关了
