### ISSUE TITLE
aapt 问题  centos 7 编译   error=2, No such file or directory  aapt文件是存在的

### ISSUE THREAD

**Issue by yangbo524** [alibaba/atlas#293]
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/app/weblogic/.gradle/caches/modules-2/files-2.1/com.taobao.android/aapt/2.3.1.rc4/593df1ae86cbee190c8fbd096adfb1b56f76d41d/aapt-2.3.1.rc4/aapt''
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:198)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:329)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
        ... 2 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/app/weblogic/.gradle/caches/modules-2/files-2.1/com.taobao.android/aapt/2.3.1.rc4/593df1ae86cbee190c8fbd096adfb1b56f76d41d/aapt-2.3.1.rc4/aapt'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
        ... 2 more
Caused by: java.io.IOException: Cannot run program "/app/weblogic/.gradle/caches/modules-2/files-2.1/com.taobao.android/aapt/2.3.1.rc4/593df1ae86cbee190c8fbd096adfb1b56f76d41d/aapt-2.3.1.rc4/aapt" (in directory ""): error=2, No such file or directory
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 4 more
Caused by: java.io.IOException: error=2, No such file or directory
        ... 5 more

**Comment by gf5353** [comment]
这篇文章可以解决 https://www.jianshu.com/p/a0830e0daea4 
sudo aptitude install lib32stdc++6 lib32z1
