### ISSUE TITLE
[use]:bundle中无法找到资源文件

### ISSUE THREAD

**Issue by zhoujunyou** [alibaba/atlas#294]
08-17 10:17:36.462 6134-6134/? D/dalvikvm: Late-enabling CheckJNI
08-17 10:17:36.466 6134-6134/? I/Zygote: fake Product info cn.mwee.android.atlasapp not matched any pattern
08-17 10:17:36.542 6134-6134/cn.mwee.android.atlasapp E/RuntimeUtils: - RuntimeUtils init: mEnabled=true
08-17 10:17:36.542 6134-6134/cn.mwee.android.atlasapp I/VMUtil: VM with version 1.6.0 does not have ART support
08-17 10:17:36.542 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: Trying to load lib /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikhack.so 0x42e23bd0
08-17 10:17:36.550 6134-6134/cn.mwee.android.atlasapp D/houdini: [6134] Loading library(version: 4.0.8.45720 RELEASE)... successfully.
08-17 10:17:36.554 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: Added shared lib /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikhack.so 0x42e23bd0
08-17 10:17:36.566 6134-6134/cn.mwee.android.atlasapp E/RuntimeUtils: - RuntimeUtils init: success=true
08-17 10:17:36.566 6134-6134/cn.mwee.android.atlasapp E/AndroidRuntime: class com.taobao.android.runtime.Dex2OatService
08-17 10:17:36.566 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: Trying to load lib /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikpatch.so 0x42e23bd0
    Added shared lib /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikpatch.so 0x42e23bd0
    No JNI_OnLoad found in /data/app-lib/cn.mwee.android.atlasapp-1/libdalvikpatch.so 0x42e23bd0, skipping init
08-17 10:17:36.582 6134-6134/cn.mwee.android.atlasapp E/DALVIK_PATCH: vm:dalvik
    Find dvmGlobalsPtr successed!
08-17 10:17:36.582 6134-6134/cn.mwee.android.atlasapp D/DALVIK_PATCH: [4][0x8]Not readable! b
    [6][0x8]Not readable! b
    [10][0x18]Not readable! b
    [11][0x10]Not readable! b
    [14][0x14]Not readable! b
    [15][0x8]Not readable! b
    [16][0x10]Not readable! b
    [17][0xc]Not readable! b
    [19][0x0]Not readable! b
08-17 10:17:36.586 6134-6134/cn.mwee.android.atlasapp D/DALVIK_PATCH: [20][0xfffd82ca]Not readable! b
    [21][0x0]Not readable! b
    [22][0x0]Not readable! b
    [23][0xffffc476]Not readable! b
    [24][0x0]Not readable! b
    [26][0x3]Not readable! b
    [27][0x0]Not readable! b
    [29][0xfc]Not readable! b
    [31][0x2]Not readable! b
    [32][0x200]Not readable! b
    [33][0xc800]Not readable! b
    [34][0x0]Not readable! b
    [36][0x3]Not readable! b
    [37][0x10]Not readable! b
    [38][0xc800]Not readable! b
08-17 10:17:36.590 6134-6134/cn.mwee.android.atlasapp D/DALVIK_PATCH: [39][0x0]Not readable! b
    [40][0x0]Not readable! b
    [43][0x10]Not readable! b
    [44][0x400]Not readable! b
    [45][0x0]Not readable! b
    [47][0x0]Not readable! b
    [48][0xffffe23e]Not readable! b
    [56][0x1]Not readable! b
    [57][0xf]Not readable! b
08-17 10:17:36.590 6134-6134/cn.mwee.android.atlasapp E/DALVIK_PATCH: ***********************************************
    => LinearAllocHdr:[0x81489520]
    => curOffset[3477172]
    => mapAddr[0x6e9f6000]
    => mapLength[16777216]
    => firstOffset[4100]
    => mapAddr: [0x6e9f6000]
    ***********************************************
    Search LinearAllocHdr cost: 10 ms!
08-17 10:17:36.594 6134-6134/cn.mwee.android.atlasapp E/DALVIK_PATCH: LinearAllocHdr.mapLength >= 16777216, don't patch dalvik!
08-17 10:17:36.594 6134-6134/cn.mwee.android.atlasapp D/DalvikPatch: - patchIfPossible: adjustLinearAlloc=-303
08-17 10:17:36.594 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-17 10:17:36.594 6134-6134/cn.mwee.android.atlasapp W/dalvikvm: VFY: unable to resolve static field 185 (PREVIEW_SDK_INT) in Landroid/os/Build$VERSION;
08-17 10:17:36.594 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: VFY: replacing opcode 0x60 at 0x0018
    DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-17 10:17:36.602 6134-6134/cn.mwee.android.atlasapp W/dalvikvm: VFY: unable to resolve static field 185 (PREVIEW_SDK_INT) in Landroid/os/Build$VERSION;
08-17 10:17:36.602 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: VFY: replacing opcode 0x60 at 0x000a
08-17 10:17:36.606 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-17 10:17:36.606 6134-6134/cn.mwee.android.atlasapp W/dalvikvm: VFY: unable to resolve static field 185 (PREVIEW_SDK_INT) in Landroid/os/Build$VERSION;
08-17 10:17:36.606 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: VFY: replacing opcode 0x60 at 0x0211
    DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-17 10:17:36.606 6134-6134/cn.mwee.android.atlasapp W/dalvikvm: VFY: unable to resolve static field 185 (PREVIEW_SDK_INT) in Landroid/os/Build$VERSION;
08-17 10:17:36.606 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: VFY: replacing opcode 0x60 at 0x0120
08-17 10:17:36.614 6134-6134/cn.mwee.android.atlasapp E/BridgeApplication: length =4029025
08-17 10:17:36.614 6134-6134/cn.mwee.android.atlasapp E/RuntimeUtils: - RuntimeUtils setVerificationEnabled: enabled=false, success=true
08-17 10:17:36.614 6134-6134/cn.mwee.android.atlasapp I/MultiDex: VM with version 1.6.0 does not have multidex support
    Installing application
08-17 10:17:36.618 6134-6134/cn.mwee.android.atlasapp I/MultiDex: MultiDexExtractor.load(/data/app/cn.mwee.android.atlasapp-1.apk, false, )
    Blocking on lock /data/data/cn.mwee.android.atlasapp/code_cache/secondary-dexes/MultiDex.lock
    /data/data/cn.mwee.android.atlasapp/code_cache/secondary-dexes/MultiDex.lock locked
    loading existing secondary dex files
    load found 0 secondary dex files
    install done
08-17 10:17:36.618 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-17 10:17:36.618 6134-6134/cn.mwee.android.atlasapp I/dalvikvm: DexOpt: unable to optimize static field ref 0x00b9 at 0x7d in Landroid/taobao/atlas/framework/Atlas;.init
08-17 10:17:36.626 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-17 10:17:36.626 6134-6134/cn.mwee.android.atlasapp I/dalvikvm: DexOpt: unable to optimize static field ref 0x00b9 at 0x34 in Landroid/taobao/atlas/runtime/newcomponent/provider/ContentProviderBridge;.call
08-17 10:17:36.626 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build$VERSION;.PREVIEW_SDK_INT
08-17 10:17:36.626 6134-6134/cn.mwee.android.atlasapp I/dalvikvm: DexOpt: unable to optimize static field ref 0x00b9 at 0x7b in Landroid/taobao/atlas/runtime/newcomponent/provider/ContentProviderBridge;.call
08-17 10:17:36.626 6134-6134/cn.mwee.android.atlasapp E/AtlasBundleInfoManager: generate info from generator
08-17 10:17:36.654 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: GC_FOR_ALLOC freed 331K, 12% free 2990K/3384K, paused 4ms, total 6ms
08-17 10:17:36.730 6134-6134/cn.mwee.android.atlasapp D/libEGL: loaded /system/lib/egl/libEGL_emulation.so
08-17 10:17:36.794 6134-6134/cn.mwee.android.atlasapp D/libEGL: loaded /system/lib/egl/libGLESv1_CM_emulation.so
    loaded /system/lib/egl/libGLESv2_emulation.so
08-17 10:17:36.818 6134-6134/cn.mwee.android.atlasapp W/EGL_emulation: eglSurfaceAttrib not implemented
08-17 10:17:36.822 6134-6134/cn.mwee.android.atlasapp D/OpenGLRenderer: Enabling debug mode 0
08-17 10:17:38.642 6134-6134/cn.mwee.android.atlasapp D/dalvikvm: GC_FOR_ALLOC freed 261K, 10% free 3240K/3564K, paused 2ms, total 3ms
08-17 10:17:38.642 6134-6155/cn.mwee.android.atlasapp E/BundleInstaller: cn.mwee.android.pay.coupon-->[cn.mwee.android.pay.coupon], thread=Thread[bundle_installer,5,main]
08-17 10:17:38.642 6134-6155/cn.mwee.android.atlasapp E/Framework: content: lock
    content: 3gfu0zmo7kqv
    restoreExisted: cn.mwee.android.pay.coupon| 3gfu0zmo7kqv| /data/data/cn.mwee.android.atlasapp/files/storage/cn.mwee.android.pay.coupon
08-17 10:17:38.646 6134-6155/cn.mwee.android.atlasapp E/BundleClassLoader: nativeLibPath : /data/data/cn.mwee.android.atlasapp/files/storage/cn.mwee.android.pay.coupon/3gfu0zmo7kqv/lib:/data/app-lib/cn.mwee.android.atlasapp-1:/vendor/lib:/system/lib:/system/lib/arm
08-17 10:17:38.646 6134-6155/cn.mwee.android.atlasapp E/BundleArchiveRevision: interpretOnly = false
08-17 10:17:38.650 6134-6155/cn.mwee.android.atlasapp E/Framework: bundle archieve dexopt bundle /data/data/cn.mwee.android.atlasapp/lib/libcn_mwee_android_pay_coupon.so cost time = 1 ms
08-17 10:17:38.682 6134-6134/cn.mwee.android.atlasapp W/EGL_emulation: eglSurfaceAttrib not implemented
08-17 10:17:38.686 6134-6134/cn.mwee.android.atlasapp E/BundleInstaller: notify finish [cn.mwee.android.pay.coupon]
08-17 10:17:38.686 6134-6134/cn.mwee.android.atlasapp E/BundleLifeCycle: started with no application
08-17 10:17:38.686 6134-6134/cn.mwee.android.atlasapp E/InstrumentationHook: async startActivity
08-17 10:17:41.166 6134-6134/cn.mwee.android.atlasapp W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.mwee.android.atlasapp/cn.mwee.android.pay.coupon.check.CheckCouponActivity}: java.lang.RuntimeException: nullPaths: [/data/app/cn.mwee.android.atlasapp-1.apk, /data/data/cn.mwee.android.atlasapp/lib/libcn_mwee_android_pay_coupon.so](2.6) DelegateResources equals Activity Resources(2.7) Activity Resources paths length:2
08-17 10:17:41.170 6134-6134/cn.mwee.android.atlasapp W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2208)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
        at android.app.ActivityThread.access$900(ActivityThread.java:137)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:283)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5089)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
        at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.RuntimeException: nullPaths: [/data/app/cn.mwee.android.atlasapp-1.apk, /data/data/cn.mwee.android.atlasapp/lib/libcn_mwee_android_pay_coupon.so](2.6) DelegateResources equals Activity Resources(2.7) Activity Resources paths length:2
        at android.taobao.atlas.runtime.InstrumentationHook.HandleResourceNotFound(InstrumentationHook.java:808)
        at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:677)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)
    	... 12 more
    Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:292)
        at android.app.Activity.setContentView(Activity.java:1937)
        at cn.mwee.android.pay.coupon.check.CheckCouponActivity.onCreate(CheckCouponActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:5263)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:671)
    	... 13 more
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
    	... 26 more
    Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x7/d=0xa2010000 a=-1}
        at android.content.res.Resources.loadDrawable(Resources.java:2068)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at android.view.View.<init>(View.java:3554)
        at android.widget.TextView.<init>(TextView.java:623)
        at android.widget.TextView.<init>(TextView.java:618)
    	... 29 more
08-17 10:17:41.174 6134-6134/cn.mwee.android.atlasapp D/AndroidRuntime: Shutting down VM
08-17 10:17:41.174 6134-6134/cn.mwee.android.atlasapp W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x42b53b20)
08-17 10:17:41.174 6134-6134/cn.mwee.android.atlasapp E/CrashManager: force stop
08-17 10:17:41.178 6134-6134/cn.mwee.android.atlasapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.mwee.android.atlasapp, PID: 6134
    java.lang.RuntimeException: 1.0
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:337)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5089)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.mwee.android.atlasapp/cn.mwee.android.pay.coupon.check.CheckCouponActivity}: java.lang.RuntimeException: nullPaths: [/data/app/cn.mwee.android.atlasapp-1.apk, /data/data/cn.mwee.android.atlasapp/lib/libcn_mwee_android_pay_coupon.so](2.6) DelegateResources equals Activity Resources(2.7) Activity Resources paths length:2
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2208)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
        at android.app.ActivityThread.access$900(ActivityThread.java:137)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:283)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.RuntimeException: nullPaths: [/data/app/cn.mwee.android.atlasapp-1.apk, /data/data/cn.mwee.android.atlasapp/lib/libcn_mwee_android_pay_coupon.so](2.6) DelegateResources equals Activity Resources(2.7) Activity Resources paths length:2
        at android.taobao.atlas.runtime.InstrumentationHook.HandleResourceNotFound(InstrumentationHook.java:808)
        at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:677)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
        at android.app.ActivityThread.access$900(ActivityThread.java:137) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:283) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:292)
        at android.app.Activity.setContentView(Activity.java:1937)
        at cn.mwee.android.pay.coupon.check.CheckCouponActivity.onCreate(CheckCouponActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:5263)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:671)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
        at android.app.ActivityThread.access$900(ActivityThread.java:137) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:283) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:292) 
        at android.app.Activity.setContentView(Activity.java:1937) 
        at cn.mwee.android.pay.coupon.check.CheckCouponActivity.onCreate(CheckCouponActivity.java:29) 
        at android.app.Activity.performCreate(Activity.java:5263) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:671) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
        at android.app.ActivityThread.access$900(ActivityThread.java:137) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:283) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x7/d=0xa2010000 a=-1}
        at android.content.res.Resources.loadDrawable(Resources.java:2068)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at android.view.View.<init>(View.java:3554)
        at android.widget.TextView.<init>(TextView.java:623)
        at android.widget.TextView.<init>(TextView.java:618)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:292) 
        at android.app.Activity.setContentView(Activity.java:1937) 
        at cn.mwee.android.pay.coupon.check.CheckCouponActivity.onCreate(CheckCouponActivity.java:29) 
        at android.app.Activity.performCreate(Activity.java:5263) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:671) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
        at android.app.ActivityThread.access$900(ActivityThread.java:137) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:283) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
        at dalvik.system.NativeStart.main(Native Method) 
08-17 10:17:41.186 6134-6134/cn.mwee.android.atlasapp I/Process: Sending signal. PID: 6134 SIG: 9

使用的com.taobao.android:atlasplugin:3.0.1-rc43 版本 
[libcn_mwee_android_pay_coupon.so](https://github.com/alibaba/atlas/files/2295775/libcn_mwee_android_pay_coupon.zip)

**Comment by hwjump** [comment]
首先你解开包用aapt看资源正确与否，其次对4.x的手机，要注意 xxx-v14的资源存在

**Comment by zhoujunyou** [comment]
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
        at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:272)
        at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1156)
        at android.content.res.TypedArray.getValueAt(TypedArray.java:1142)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:865)
        at android.view.View.<init>(View.java:3963)
        at android.widget.ImageView.<init>(ImageView.java:145)
        at android.widget.ImageView.<init>(ImageView.java:140)
        at android.widget.ImageView.<init>(ImageView.java:136)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at cn.mwee.android.pay.coupon.coupons.SearchCouponDialogFragment.onCreateView(SearchCouponDialogFragment.java:81) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149) 
        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
6.x的设备上出现了这个问题  反编译了so 资源是存在的 。

**Comment by zhoujunyou** [comment]
开启了aapt2在bundle中的布局中资源id反编译出来是这种形式<0xA2xxxxxx,type 0x07>.  如果将资源放置host中id 就是0x7fxxxxxx这种形式是没问题的   是我漏了配置什么参数吗？

**Comment by zhoujunyou** [comment]
把aapt2禁用了 上面的问题都正常了。话说现在是还不支持aapt2吗？
