### ISSUE TITLE
process res exception

### ISSUE THREAD

**Issue by caokunhk** [alibaba/atlas#319]
Caused by: com.android.ide.common.process.ProcessException: Error while executing process C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.taobao.android\aapt\2.3.1.rc4\593df1ae86cbee190c8fbd096adfb1b56f76d41d\aapt-2.3.1.rc4\aapt.exe with arguments {package -f --no-crunch -I D:\tools\sdk\sdk\platforms\android-25\android.jar -M E:\git\atlas-master\atlas-master\atlas-demo\AtlasDemo\app\build\intermediates\awb-manifests\full\debug\com.atlas.demo-firstbundle\AndroidManifest.xml -S E:\git\atlas-master\atlas-master\atlas-demo\AtlasDemo\app\build\intermediates\awb-res\merged\debug\com.atlas.demo-firstbundle -A E:\git\atlas-master\atlas-master\atlas-demo\AtlasDemo\app\build\intermediates\awb-assets\debug\com.atlas.demo-firstbundle -m -J E:\git\atlas-master\atlas-master\atlas-demo\AtlasDemo\app\build\generated\source\awb-r\debug\com.atlas.demo-firstbundle -F E:\git\atlas-master\atlas-master\atlas-demo\AtlasDemo\app\build\intermediates\res\com.atlas.demo-firstbundle\resources-debug.ap_ --debug-mode --custom-package com.taobao.firstbundle -0 apk --forced-package-id 36 --main-package com.taobao.demo -I E:\git\atlas-master\atlas-master\atlas-demo\AtlasDemo\app\build\intermediates\res\resources-debug.ap_ --preferred-density xxhdpi --no-version-vectors --output-text-symbols E:\git\atlas-master\atlas-master\atlas-demo\AtlasDemo\app\build\intermediates\awb-symbols\debug\com.atlas.demo-firstbundle}
	at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:74)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:49)
	at com.android.builder.core.AtlasBuilder.processAwbResources(AtlasBuilder.java:674)
	at com.taobao.android.builder.tasks.app.bundle.ProcessAwbAndroidResources.doFullTaskAction(ProcessAwbAndroidResources.java:376)
	... 11 more
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.taobao.android\aapt\2.3.1.rc4\593df1ae86cbee190c8fbd096adfb1b56f76d41d\aapt-2.3.1.rc4\aapt.exe'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:369)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:47)
	... 13 more

**Comment by hwjump** [comment]
这是是处理资源错误了。可以命令行加下 --info看到底哪个资源处了问题。试下
