### ISSUE TITLE
[use] KernalBundle.patchKernalDex NullPointerException

### ISSUE THREAD

**Issue by caizhibiao** [alibaba/atlas#349]
Android 4.4
进行热修复部署时，对差分包进行合并时出现空指针。
W/System.err( 3886): java.lang.NullPointerException
W/System.err( 3886): 	at android.taobao.atlas.startup.patch.KernalBundle.patchKernalDex(KernalBundle.java:420)
W/System.err( 3886): 	at android.taobao.atlas.startup.patch.KernalBundle.checkloadKernalBundle(KernalBundle.java:276)
W/System.err( 3886): 	at android.taobao.atlas.startup.AtlasBridgeApplication.attachBaseContext(AtlasBridgeApplication.java:295)

看源码是FrameworkPropertiesClazz为空导致。
            if(FrameworkPropertiesClazz==null && isDeubgMode()){
                Log.e("KernalBundle","main dex is not match, library awo test?");
                return;
            }
            Field versionField = FrameworkPropertiesClazz.getDeclaredField("version");

main dex is not match, library awo test是什么意思？ 差分包不正确导致？

**Comment by caizhibiao** [comment]
atlas版本  
    lib_atlas_core = "com.taobao.android:atlas_core:5.0.7.55@aar"
    lib_atlas_update = "com.taobao.android:atlasupdate:1.1.4.14@aar"

**Comment by tachea929-commits** [comment]
![Image](https://github.com/user-attachments/assets/bcad8f0c-b269-46cd-b718-b50960d0bede)
