### ISSUE TITLE
加载远程bundle失败

### ISSUE THREAD

**Issue by ZhangKuixun** [alibaba/atlas#375]
加载远程bundle失败
```
09-23 17:38:22.070 29694-29694/com.taobao.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.taobao.demo, PID: 29694
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.taobao.demo/com.taobao.remotebunle.RemoteBundleActivity}: java.lang.ClassNotFoundException: Didn't find class "com.taobao.remotebunle.RemoteBundleActivity" on path: DexPathList[[zip file "/data/app/com.taobao.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.demo-2/lib/arm, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2538)
        at android.app.ActivityThread.access$1000(ActivityThread.java:168)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5589)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.remotebunle.RemoteBundleActivity" on path: DexPathList[[zip file "/data/app/com.taobao.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.demo-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1070)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2538) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:168) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5589) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751) 
    	Suppressed: java.lang.ClassNotFoundException: com.taobao.remotebunle.RemoteBundleActivity
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 13 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by yjj025Android** [comment]
请问有解决吗？卡在这一步了。
