### ISSUE TITLE
Keyframe containsProgress error 

### ISSUE THREAD

**Issue by tuananhdtu** [alibaba/atlas#387]
Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at com.airbnb.lottie.value.Keyframe.containsProgress(Keyframe.java:124)
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation$KeyframesWrapperImpl.isValueChanged(BaseKeyframeAnimation.java:297)
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.setProgress(BaseKeyframeAnimation.java:62)
       at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:553)
       at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:137)
       at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:154)
       at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:70)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
       at com.airbnb.lottie.utils.LottieValueAnimator.setFrame(LottieValueAnimator.java:159)
       at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:208)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:449)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieDrawable$2.run(LottieDrawable.java:442)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:220)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:564)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:85)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:83)
       at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
       at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by tuananhdtu** [comment]
Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.setProgress(TransformKeyframeAnimation.java:126)
       at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:542)
       at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:137)
       at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:154)
       at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:70)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
       at com.airbnb.lottie.utils.LottieValueAnimator.setFrame(LottieValueAnimator.java:159)
       at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:208)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:449)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
       at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
       at com.airbnb.lottie.LottieDrawable$2.run(LottieDrawable.java:442)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:220)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:564)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:85)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:83)
       at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
       at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
