### ISSUE TITLE
Demo中 问题2：如何在用户无感知的情况下，实现所有业务模块的独立动态更新？不能是实现 手机是小米手机

### ISSUE THREAD

**Issue by chenxiaokai** [alibaba/atlas#70]
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.taobao.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.demo-1/lib/arm64, /data/app/com.taobao.demo-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libdalvikpatch.so"
                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.taobao.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.demo-1/lib/arm64, /data/app/com.taobao.demo-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libdalvikpatch.so"
                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                  at java.lang.System.loadLibrary(System.java:1076)
                                                                  at com.uc.browser.aerie.DalvikPatch.patchIfPossible(DalvikPatch.java:12)
                                                                  at android.taobao.atlas.util.DexLoadBooster.init(DexLoadBooster.java:245)
                                                                  at android.taobao.atlas.framework.Atlas.startup(Atlas.java:352)
                                                                  at android.taobao.atlas.bridge.BridgeApplicationDelegate.onCreate(BridgeApplicationDelegate.java:406)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at android.taobao.atlas.startup.AtlasBridgeApplication.onCreate(AtlasBridgeApplication.java:351)
                                                                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
                                                                  at android.taobao.atlas.runtime.InstrumentationHook.callApplicationOnCreate(InstrumentationHook.java:1048)
                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4930)
                                                                  at android.app.ActivityThread.access$1600(ActivityThread.java:180)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5710)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

**Comment by hwjump** [comment]
已经修复，请下载最新工程
